### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/SetEdit#1]
@IzzySoft

**Comment by IzzySoft** [comment]
Heh, that's a kind of delegation, just dropping my name :grimacing: May I kindly ask to open an RFP with F-Droid, or open an issue in my tracker, for future requests? :hugs:

For the current one: Any screenshots you'd like to provide via Fastlane (you're welcome to pick them from my repo, I've just created some – clock indicates app version)? All the description says about what you can do with the app is that it's a FOSS version of some other app – so if one doesn't know that, one can only guess (you might want to add some hints to `full_description.txt` as well as adjust `short_description.txt` to give some clue – again, feel free to copy from my updated description, and use e.g. `<code>pm grant…</code>`, which is permitted in the full description via Fastlane, as are other simple HTML tags).

So thanks for the pointer, and your app will go live in my repo in about 5 hours. For F-Droid.org, please open an RFP, I'll add the metadata there then (as I already have them set up anyway here).

**Comment by MuntashirAkon** [comment]
Didn't know Github allows multiple reactions for a single comment :) I only mention you because I'm very disappointed with F-Droid of late. It's been two months and they still didn't push my other app (App Manager). But yeah, I've now two RFPs to make. (I guess I'm very busy with developing than actually releasing anything right now.) Anyway, I enjoy reading your comments which made me do it in first place.

**Comment by MuntashirAkon** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1438

**Comment by IzzySoft** [comment]
Yeah, count me in. I always try to hurry up and react fast, then the RFPs sit on "ready" for "eternity". No problem in mentioning me – it just looks weird if that's all the content a comment has. I know you didn't mean it that way, so please don't get me wrong – but it looks like "there's something to do, so please figure it out, Izzy" :wink:

Of course it's fine to handle it here. Having it in RFP (or my corresponding tracker) makes it easier to look things up sometimes. And I'm also fine serving your apps via my repo, if fast updates and quick reactions are more important to you than the prestige of F-Droid.org (yes, I know my repo never can reach that trust, and that's OK with me).

**Comment by MuntashirAkon** [comment]
> I know my repo never can reach that trust, and that's OK with me

That's OK with me (and many other people) as well.

> I'm also fine serving your apps via my repo, if fast updates and quick reactions are more important to you than the prestige of F-Droid.org

An F-Droid repo is like a black hole: once deployed, you do not really know what's happening there right now but I like it that way. Since I've been contributing to projects for various platforms for sometime now, I do get some weird emails now and then asking for help with a project I don't remember. But I like the fact that I've helped somebody. I think you do way better than us by putting these apps on the market in the first place. If I stopped my contributions to App Manager until it was accepted F-Droid, the app would probably never to go to where it is now as I would soon loose interest in it. Now I found myself dealing with a small community on Telegram and some random emails from people I will probably never know or meet. When you're giving effort to something voluntarily, this is what keeps you going.

**Comment by IzzySoft** [comment]
Yes indeed! I totally agree. And thanks for the warm words towards me!

**Comment by IzzySoft** [comment]
It's not yet there, but soon will be :smiley: Give it about a week for the build-sign-index cycle. And what did we decide regarding my repo? Keep or kick? Some pros and cons as usual in my repo's [FAQ](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ). I normally remove apps about a week after they showed up at F-Droid.org – unless there's special demand to keep them. So I'll leave the decision with you :wink:

**Comment by MuntashirAkon** [comment]
> And what did we decide regarding my repo?

You can remove it from the repo once it's on F-Droid.

**Comment by IzzySoft** [comment]
Thanks, will do!
