### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by rajarshikhatua100** [MuntashirAkon/SetEdit#10]
Plese provide an another app that can store the changes and restore it with one tap after reboot in setedit app,it is so difficult to restore all the changes after restarting the phone

**Comment by MuntashirAkon** [comment]
Why not in the same app?

**Comment by Taudris** [comment]
That would be even better!

**Comment by rajarshikhatua100** [comment]
this app https://play.google.com/store/apps/details?id=com.netvor.settings.database.editor from Play Store does it by creating a backup

**Comment by MuntashirAkon** [comment]
Implemented in 661a52214b4c0403b44f41fb42a2bc7f8a7d0337
