### ISSUE TITLE
Shortcut widget to quickly modify a setting item

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/SetEdit#11]
A shortcut widget would greatly help user quickly modify a setting without opening the app itself.

---

This feature was requested via email

**Comment by ferreol-fr** [comment]
Hi [MuntashirAkon](https://github.com/MuntashirAkon)
My fork : [SetEditPlus](https://github.com/ferreol-fr/SetEditPlus) is now near ready.
It adds the ability to create shortcuts for automation, with the ability to edit and modify.
I've done this with my spare time, for learning Android development environment.
I am conscious that this application, and especially mine, is dangerous and potentially catastrophic for an uninformed user.
I may have taken the liberty, more than I should have, to modify your code. Sometimes it was to fix Android Studio warnings, but mostly to make the code more readable for me.
I would really appreciate it if you could take a look at what I have done, and give me your opinion.

**Comment by MuntashirAkon** [comment]
Thanks. I'll look into it in my free time. If you think you've done a good job, consider opening a pull request to this repo so that the feature can be included in this app.

**Comment by MuntashirAkon** [comment]
Implemented in 9582528a9dc2a8d926d73e2fd9ea72d08cd67510
