### ISSUE TITLE
In my application is not possible to put value into Settings.System

### ISSUE THREAD

**Issue by henrichg** [MuntashirAkon/SetEdit#16]
Please help me.

1. WRITE_SETTINGS granted
2. WRITE_SECURE_SETTINGS granted

but is not possible to put value into, for example, System.VIB_RECVCALL_MAGNITUDE.
It is Samsung Galaxy S10 specific parameter.

In your apllication (from Google Play) is possible to edit this value and new value is reflected in S10 Settings.

But in my application is generated expetion:
`java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.`

even when used is put the value, using ContentResolver from your source code.

Thank you very much for help me.

**Comment by Taxit0m** [comment]
Its not my code, it's giving you what's wrong in the output. It says invalid argument you cannot keep your settings in secure settings. So this means it doesn't want you to add rules into the secure settings table. Try adding a rule to the system or global settings tables and if its a bit of java I think there is even a settigs table for java, I'd like to see an option for editing the build.prop but I'm not sure that it weighs a whole lot with the newer versions of android.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by henrichg** [comment]
Parameter is in Settings.System not Secure. 
`Settings.System.putInt(appContext.getContentResolver(), "VIB_RECVCALL_MAGNITUDE", value);`, exception, 

from SetEdit code, exception:

```
ContentResolver contentResolver = context.getContentResolver();
try {
    ContentValues contentValues = new ContentValues(2);
    contentValues.put("name", "VIB_RECVCALL_MAGNITUDE");
    contentValues.put("value", value);
    contentResolver.insert(Uri.parse("content://settings/" + "system"), contentValues);
} catch (Exception e) {
    Log.e("ActivateProfileHelper.setVibrationIntensity", Log.getStackTraceString(e));
}

```

**Comment by Taxit0m** [comment]
There are other forks, I usually try the most currently updated one on GitHub and there is an official release on f-droid that is really good

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MuntashirAkon** [comment]
> Hm, hm, maybe problem is targetSDK. For SetEdit it is 22, for my application it is 28.

Yes. Target SDK must be less than 23 because these permissions have the `pre23` flag.

**Comment by henrichg** [comment]
Thank you very much.
