### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [MuntashirAkon/SetEdit#19]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-03-06-23-15-58-113_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/223214689-15f227cd-453a-4f78-aa96-69fa301b914f.jpg)

**Comment by MuntashirAkon** [comment]
Let's see if I still have the artwork.

**Comment by drogga** [comment]
https://github.com/MuntashirAkon/SetEdit/blob/master/fastlane/metadata/android/en-US/images/icon.png

**Comment by RokeJulianLockhart** [comment]
> https://github.com/MuntashirAkon/SetEdit/issues/19#issuecomment-1941173722

@MuntashirAkon, the compiled APKs might contain a vector version (https://developer.android.com/studio/write/vector-asset-studio#apilevel) so I'd be surprised if it wasn't at least extractable from them, cached in the CI, and/or in the repository, considering the icon had to come from somewhere before it was packaged.

**Comment by MuntashirAkon** [comment]
Added via b6718b1bbf9db195a93df39415060b2f26f5d958. I don't know how it looks though as I've got no way to test it.
