### ISSUE TITLE
Support editing Android properties

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/SetEdit#2]
Add support for editing Android properties.

**Comment by drogga** [comment]
@MuntashirAkon isn't this already added and can be closed or deleted...?

**Comment by MuntashirAkon** [comment]
> @MuntashirAkon isn't this already added and can be closed or deleted...?

No, it's not.

**Comment by MuntashirAkon** [comment]
> what Android properties are missing? I'm no AOSP or Android ROM dev, but it seems pretty comprehensive. Is there anything noteworthy absent?

Are you familiar with build.prop files? Most of the properties are taken from these files.

**Comment by rokejulianlockhart** [comment]
@MuntashirAkon, no, I am not, but it seems like there's a lot of info on the internet, so thanks for the pointer.

**Comment by MuntashirAkon** [comment]
Added via 04230d8bdd3ffa18c11148eadd4ddb472ba5f5e6
