### ISSUE TITLE
Add support  shizuku 

### ISSUE THREAD

**Issue by Stu75e** [MuntashirAkon/SetEdit#22]

**Comment by MuntashirAkon** [comment]
None of my projects promote or support non-free apps.

**Comment by Stu75e** [comment]
Shizuku is an open source program that provides access to ADB using its own API. You can view the source of the program on GitHub.

https://github.com/RikkaApps/Shizuku

**Comment by MuntashirAkon** [comment]
> Shizuku is an open source program that provides access to ADB using its own API. You can view the source of the program on GitHub.

Open source, yes, but not [Free and Open Source](https://en.wikipedia.org/wiki/Free_and_open-source_software). It has Apache-2.0 license, but it forbids other people from reproducing/replicating the software, which effectively makes the project non-free and source-available only.

> https://github.com/RikkaApps/Shizuku

Navigate to the bottom and you'll see the following exception to the license:

> 2. For the project as a whole, it is not free. You are FORBIDDEN to distribute the apk compiled by you (including modified, e.g., rename app name "Shizuku" to something else) to any store (IBNLT Google Play Store, F-Droid, Amazon Appstore etc.).

**Comment by rajarshikhatua** [comment]
Unfortunately, [Shizuku](https://github.com/RikkaApps/Shizuku) effectively became abandonware, and the devs have no interest in developing it. There are a bunch of open pull requests with no response from the devs, so others [forked](https://github.com/thedjchi/Shizuku) it with added features with little regard for the [licence](https://github.com/thedjchi/Shizuku/issues/78#issuecomment-3649441701). Now most of the community uses the fork.
