### ISSUE TITLE
How every entry of new setting working technically behind and programmatically?

### ISSUE THREAD

**Issue by Yuva-Andrez** [MuntashirAkon/SetEdit#23]

**Comment by MuntashirAkon** [comment]
Nothing extra-ordinary. It uses [`android.provider.Settings`](https://developer.android.com/reference/android/provider/Settings) class to manage settings, including creating new items. This class basically a front-end for the settings XML files stored in the data partition. The availability of a setting, it's value, etc. depend on Android version and vendor.
