### ISSUE TITLE
Add support for Android 14

### ISSUE THREAD

**Issue by eiqnepm** [MuntashirAkon/SetEdit#24]
I have tried installing SetEdit on a at least three Android 14 devices and every one of them fails to install.

**Comment by drogga** [comment]
Ofc. it will fail/refuse to install it, apps with a targetSdkVersion lower than 23 can't be installed on A.14 and on this one the targetSdk is 22 on purpose, you can use `adb install --bypass-low-target-sdk-block` FILENAME.apk to force it to install, but IDK if it will work or will it accept any changes to any of the editable 2 tables after you activate it with another command.

**Comment by drogga** [comment]
So you are claiming that you have it installed from before updating to A.14, so what's the question here exactly ?

**Comment by MuntashirAkon** [comment]
Added instructions via 1015f102fa9d97a6a1c286fc7d22db6884dc03f1
