### ISSUE TITLE
pm grant io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by andersonxit444** [MuntashirAkon/SetEdit#25]

**Comment by drogga** [comment]
Yes, that's the correct command, ...and...?
No context, just the command as the issue name/label, but what about it ?

**Comment by MuntashirAkon** [comment]
Seems to be a spam. Similar incidents have been reported in other repositories as well.

**Comment by drogga** [comment]
If it was in my repo, I would've straight up deleted the ticket, but if you reported him, GH will probably take care, along with his account, the same way they did when I reported 1 on /butzist/ActivityLauncher, where I'm a collaborator.
