### ISSUE TITLE
Keyboard does not come up when clicking the edit field.

### ISSUE THREAD

**Issue by LucioAmely** [MuntashirAkon/SetEdit#27]
This bug exists in all versions of the app since the 2.0 revision and it's been there for years. I believe it's time to fix it has come. v1.2 is not affected by this bug. Can not get virtual keyboard open in any way to change the values. Like it's not recognizing the input field as input field at all. I've only encountered this bug in this application in my life. Using Gboard on vanilla AndroidOne 7.1.2

Also would be awesome to implement functionality of this app into your App Manager as it already has a similar feature "System Editor". Would be so good if this app's functionality can be merged into it.

**Comment by MuntashirAkon** [comment]
I was unable to reproduce your issue, unfortunately, in my Android 11 device running the AOSP keyboard. If you can still reproduce it, can you, may be share a bit more on the topic?

App Manager is meant for managing applications, not Android settings. Its use-cases are different than SetEdit. I agree that there's a room for improvement. But it is meant to be a FOSS replacement for the app by the same name. Unfortunately, I have neither the time nor the resources to improve it to a level that would be more usable to the user (user contributions are welcome, but such contributions are very rare). System UI Tuner is a good replacement if you need some specific changes to be made in the settings database. I wish I can do more, but there's a limit on the amount of things a solo developer can do.

**Comment by MuntashirAkon** [comment]
Please check again in v3.0-rc01

**Comment by LucioAmely** [comment]
> Please check again in v3.0-rc01

It works perfectly fine now. Thank you greatly for taking your time to update the app and implementing root access request feature.

**Comment by drogga** [comment]
@LucioAmely
In that case please close this issue ticket (you should be able to).

**Comment by LucioAmely** [comment]
Alright, thank you.
