### ISSUE TITLE
Android 14 isn't supported 

### ISSUE THREAD

**Issue by RootedBeing** [MuntashirAkon/SetEdit#29]
In my Device(Android 14) SetEdit Can't be used and give error everytime I want to edit a setting.
(
![Screenshot_2024-02-09-17-36-56-86_6a184d849e5092c7b27b51b62065679d](https://github.com/MuntashirAkon/SetEdit/assets/159539700/cef558f1-a3bd-45e6-9642-40eeb050f43d)

**Comment by MuntashirAkon** [comment]
It's not _this_ SetEdit app.

**Comment by RootedBeing** [comment]
> It's not _this_ SetEdit app.

_this_ Setedit isn't compatible with A14

**Comment by RootedBeing** [comment]
[](url)
![Uploading Screenshot_2024-02-13-16-09-08-26_3d73e98b1ad3bd2575f7a56513d89a0c.jpg…]()

**Comment by MuntashirAkon** [comment]
You need to install the app via ADB with the option `--bypass-low-target-sdk-block`. The app has to target API 22, otherwise it won't work at all.
