### ISSUE TITLE
Public service announcement

### ISSUE THREAD

**Issue by CamsShaft** [MuntashirAkon/SetEdit#30]
DO NOT SET ACCESS_CONTROL_ENABLED TO 1!!! Hahaha it was an interesting time to say the least. Please just don't do it. Why is that even an option?? So stupid

**Comment by MuntashirAkon** [comment]
Perhaps, you didn't read the disclaimer.

**Comment by CamsShaft** [comment]
Jesus man, I was giving a heads up so other people would be aware of the specific danger of that one. Guess I'll just keep these things to myself from now on since every comment I make gets me in shit

**Comment by MuntashirAkon** [comment]
There are many setting items that are considered extremely dangerous. But specifying them here won't help users, because a random user won't check this issue tracker before changing those items.
