### ISSUE TITLE
Settings on reboot doesn't work

### ISSUE THREAD

**Issue by dtrail** [MuntashirAkon/SetEdit#35]
With the latest release, the option to set on boot doesn't work. Actually if you tick the box, it will be unticked, it you open the same setting again. And after reboot, the values are back to default.

MI 10 on MIUI 14, Android 13.

**Comment by MuntashirAkon** [comment]
> Actually if you tick the box, it will be unticked, it you open the same setting again.

I don't understand what you're saying here. You can find a list of settings to be applied on boot in the “Boot Items” table.

**Comment by dtrail** [comment]
I'm sorry for the late reply.

I don't know, what happened. I've set my settings to apply on reboot, and it just didn't do it. But later the app received an update, and since then it works fine.
