### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/SetEdit#4]
SetEdit are only for older android devices?
Trying to launch in realme 5i Android Q
A Message Always Show That This App Are Designed For Older Android Version?????

@MuntashirAkon

**Comment by MuntashirAkon** [comment]
> SetEdit are only for older android devices?

No.

> A Message Always Show That This App Are Designed For Older Android Version?????

SetEdit targets an older API so that you can edit setting items without root. It perfectly works in Android Q or R.

**Comment by NSTAdventure** [comment]
It's a mario time! @MuntashirAkon 

Thanks for clarification
