### ISSUE TITLE
Cannot install on Android 14 anymore

### ISSUE THREAD

**Issue by erayrafet** [MuntashirAkon/SetEdit#44]
Google is blocking apps targeting old Android versions from installing and SetEdit is set to Android L. Modifying the target version of the app makes it installable.

**Comment by MuntashirAkon** [comment]
> Google is blocking apps targeting old Android versions from installing and SetEdit is set to Android L.

You can use ADB to install it by bypassing the SDK requirement.

> Modifying the target version of the app makes it installable.

Yes, but it would make some features unusable which is why the app was developed in first place.

**Comment by erayrafet** [comment]
It barely has any features – only one. Plus there's a 2023 build of original SetEdit on the Play Store.
