### ISSUE TITLE
What command should I run to give permission to SetEdit

### ISSUE THREAD

**Issue by shouyou10** [MuntashirAkon/SetEdit#6]
I am using the F-droid version of "SetEdit" apk. I command given on the F-droid description is not working for me. Can you please tell me what measures should I take in details?

**Comment by drogga** [comment]
@MuntashirAkon If you want\like, you can edit the ReadMe.md to include the link to F-Droid, the description from there, especially the command (just like it is in my comment above - in "code") ;)

**Comment by drogga** [comment]
@MuntashirAkon If you want\like, you can edit the ReadMe.md to include the link to F-Droid, and the description from there, especially the command _(just like it is in my comment above - in "code")_ ;)

**Comment by MuntashirAkon** [comment]
@drogga Thanks. I'll add the link to the F-Droid repo as well as the description from there.

**Comment by drogga** [comment]
OK, thanks. I think that you can close this 'issue' once it's done.

**Comment by MuntashirAkon** [comment]
Fixed in 1795074

**Comment by Protey** [comment]
I hope I did the right thing by raising the old branch so as not to create a new one of the same)
I can't get permission for the SetEdit application, i.e. it is issued, but the SetEdit application still asks for permission.
![image](https://user-images.githubusercontent.com/6497045/222146648-a673d458-8652-4250-b7a3-e56cadab255f.png)

I specially downloaded the SetEdit application from the Play Market, also gave it permission, and everything works without problems, BUT I would like to use your application since it has a search, it's very convenient!

**Comment by MuntashirAkon** [comment]
> I can't get permission for the SetEdit application, i.e. it is issued, but the SetEdit application still asks for permission.

Quite unusual. Use another app such as App Manager to check if the permission was actually granted to SetEdit.

**Comment by Protey** [comment]
> Quite unusual. Use another app such as App Manager to check if the permission was actually granted to SetEdit.

I have never used the App Manager, downloaded it from the Play Market, and I do not know where, and how, to see that permission has been granted.

**Comment by MuntashirAkon** [comment]
> I have never used the App Manager, downloaded it from the Play Market, and I do not know where, and how, to see that permission has been granted.

I mean this App Manager: https://github.com/MuntashirAkon/AppManager/ (It's not available on Play Store).

**Comment by Protey** [comment]
> > I have never used the App Manager, downloaded it from the Play Market, and I do not know where, and how, to see that permission has been granted.
> 
> I mean this App Manager: https://github.com/MuntashirAkon/AppManager/ (It's not available on Play Store).

Do you need to show the "Uses permissions" tab, or the "Permissions" tab?

**Comment by MuntashirAkon** [comment]
> Do you need to show the "Uses permissions" tab, or the "Permissions" tab?

In uses permissions tab, check if `WRITE_SECURE_SETTINGS` permission is granted.

**Comment by Protey** [comment]
Here is a screenshot of the Settings Database Editor application
![image](https://user-images.githubusercontent.com/6497045/222234201-6ff94807-213f-4394-836b-215e8e2f82fd.png)

Here is a screenshot of the app, from the Play Market, 4A Settings Database Editor
![image](https://user-images.githubusercontent.com/6497045/222234426-05401085-d938-4daf-a971-ded6ecc6afa2.png)

As I said above, I got access through 4A Settings Database Editor without any problems, but not through Settings Database Editor, Settings Database Editor still asks me to grant access.
![image](https://user-images.githubusercontent.com/6497045/222235229-b25c711c-2891-4e87-b350-5f58ca43017c.png)

**Comment by MuntashirAkon** [comment]
> Here is a screenshot of the Settings Database Editor application

As you can see in the screenshot, you haven't granted SetEdit the permission.

**Comment by Protey** [comment]
> As you can see in the screenshot, you haven't granted SetEdit the permission.
By what criteria did you see it?

Well, and, in my defense, I will answer - I provided a screenshot of the command line above, where I gave SetEdit permission, but it still asks for permission

**Comment by MuntashirAkon** [comment]
> By what criteria did you see it?
> Well, and, in my defense, I will answer - I provided a screenshot of the command line above, where I gave SetEdit permission, but it still asks for permission

Screenshot says you haven't granted the permission. So, a better option would be to try running that command again. This time check the name of the package and permission correctly, or set the mode of operation in App Manager to ADB, connect it to ADB and grant the permission there.

**Comment by Protey** [comment]
> Screenshot says you haven't granted the permission.

Sorry, I still can't see where in my screenshot you saw that permission was not granted, can you please indicate where on my screenshot?

> So, a better option would be to try running that command again. This time check the name of the package and permission correctly, or set the mode of operation in App Manager to ADB, connect it to ADB and grant the permission there.

I'll try again, but I'm still interested in how you determine through the App Manager whether permission is granted or not.

**Comment by Protey** [comment]
This is some kind of nonsense, I tried to grant permissions 5 times, everything is useless!
![image](https://user-images.githubusercontent.com/6497045/222250978-7a496c76-9a08-4442-9a9a-19e61ec5e6fd.png)
![image](https://user-images.githubusercontent.com/6497045/222251327-4bec0055-db2a-438f-9f7c-98fe5c4cd5c5.png)

**Comment by MuntashirAkon** [comment]
> Sorry, I still can't see where in my screenshot you saw that permission was not granted, can you please indicate where on my screenshot?

See the highlighted section below. It says revoked but it should say granted.

![222234201-6ff94807-213f-4394-836b-215e8e2f82fd](https://user-images.githubusercontent.com/8176128/222257997-662c46ec-8045-4f83-979d-50d109284792.png)

**Comment by MuntashirAkon** [comment]
> This is some kind of nonsense, I tried to grant permissions 5 times, I even downloaded it again SDK Platform-Tools for Windows, everything is useless!

Try using App Manager to grant the permission. If there is an issue with granting the permission, App Manager will report it.

To do this, you'd need to enable ADB mode in App Manager > Settings > Mode of Operation after enabling Wireless debugging or ADB over TCP.

**Comment by Protey** [comment]
> Try using App Manager to grant the permission. If there is an issue with granting the permission, App Manager will report it.
> 
> To do this, you'd need to enable ADB mode in App Manager > Settings > Mode of Operation after enabling Wireless debugging or ADB over TCP.

It's getting ridiculous, and at the same time I want to cry, I turn on the resolution, update it, and it immediately turns off.
https://user-images.githubusercontent.com/6497045/222262190-a2e7e74f-38d9-4f42-ae5b-0a3ba88e412e.mp4

**Comment by MuntashirAkon** [comment]
> It's getting ridiculous, and at the same time I want to cry, I turn on the resolution, update it, and it immediately turns off.

Which device/OS is this? Never saw anything like it before.

**Comment by Protey** [comment]
> Which device/OS is this? Never saw anything like it before.

Tecno Spark 8C KG5n, Android 11

**Comment by MuntashirAkon** [comment]
Have you tried reinstalling the app? Uninstall the app, restart your device and then install the app again. Permissions are managed by Android framework (via package_restrictions.xml). There's no reason for it working on one user app but not on another.

**Comment by Protey** [comment]
> Have you tried reinstalling the app? Uninstall the app, restart your device and then install the app again. Permissions are managed by Android framework (via package_restrictions.xml). There's no reason for it working on one user app but not on another.

Thank you, it really helped!
Just in case, I will write the steps of actions for those who will have the same problem.
1) Deleted the 4A Settings Database Editor application and your SetEdit application.
2) Rebooted the phone.
3) Re-downloaded SetEdit from the repository https://github.com/MuntashirAkon/SetEdit/releases/tag/v2.3, and installed it.
4) Without launching SetEdit, launched the [AppManager] application (https://github.com/MuntashirAkon/AppManager /), and in the AppManager application gave, without any problems, the necessary permissions.
5) I launched the SetEdit application, to check, everything is fine, the application has permission.

**Comment by drogga** [comment]
I think it's better if don't link to the current version tag, because this will change in future (there will be new vers.), but your link in those steps will still point to v2.3 and, which will be outdated then.

BTW, commenting because for some reason the notification I got here said that I was mentioned, but I wasn't, should've said "commented" - stupid GitHub...

_There's a fork of this with a better UI (in my opinion) on Play Store..._

**Comment by Protey** [comment]
> I think it's better if you don't link to the current version tag, because this will change in future (there will be new vers.), but your link in those steps will still point to v2.3, which will be outdated then.

well, I was hoping that others would understand that this may be applicable to other versions, but you're probably right, I fixed the link for this)

**Comment by Mkcein** [comment]
> @shouyou10 - It is working (make sure you don't use the 'original' from PlayStore, cuz it's with a different Package Name) !
> 
> ```
> adb shell
> pm grant io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS
> ```

which command should I use for an app that is within my WORK PROFILE (SHELTER) the user it is is is 11 which command should I give to change the permissions from that user for this same code you posted above?

        UserInfo{0:PRINCIPAL:c13} running
        UserInfo{10:BANCOS:410} running
        UserInfo{11:Perfil de trabalho:1030} running

**Comment by drogga** [comment]
IDK, but I guess `adb shell pm grant --user <USER_ID>`, example: `--user 0`

**Comment by drogga** [comment]
IDK, but I guess: `adb shell` `pm grant --user <USER_ID>`, example: `--user 1`
In your case I guess: `pm grant --user 11 io.github.muntashirakon.setedit android.permission.WRITE_SECURE_SETTINGS`, but IDK if it will work...
Doesn't it just work while you are logged in that profile to just run the command, without specifying the user ID numebr ?
