### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by NSTAdventure** [MuntashirAkon/SetEdit#9]
1. do we need restart everytime we edit system setting use Setedit?

Suggestion:
disroot search causing many redirects Everytime i tried to visit one if disroot search result pls replace it with other search engine

**Comment by drogga** [comment]
@NSTAdventure Not necessarily - I think, but it depends.
I suggested @MuntashirAkon the same thing, even tho I can mod to replace it for myself back to G or basically any other engine...

**Comment by MuntashirAkon** [comment]
> 1. do we need restart everytime we edit system setting use Setedit?

Yes. They are not immediately applied by the system (unlike the two other tables).

**Comment by NSTAdventure** [comment]
> > 1. do we need restart everytime we edit system setting use Setedit?
> 
> Yes. They are not immediately applied by the system (unlike the two other tables).

bro why you close this one? i also have suggestions above that you may consider it first 🙏
